### ISSUE TITLE
MoST with SUMO 1.9.2

### ISSUE THREAD

**Issue by awillecke** [lcodeca/MoSTScenario#8]
Hi,

we would like to run the MoST scenario with a more recent version of SUMO (1.9.2).

We noticed that at certain locations, traffic is piling up at intersections using 1.3.1 which does not happen in 1.9.2.

First example:
With SUMO 1.3.1:
![SUMO 1.3.1](https://user-images.githubusercontent.com/4274367/123809920-87a65c00-d8e1-11eb-8460-65e9e2eb819f.png)
and with SUMO 1.9.2:
![SUMO 1.9.2](https://user-images.githubusercontent.com/4274367/123810032-9f7de000-d8e1-11eb-8149-6d1f09865042.png)

Second example:
With SUMO 1.3.1:
![most_with_sumo1 3 1_2](https://user-images.githubusercontent.com/4274367/123811057-714cd000-d8e2-11eb-842b-71c6c6f65aad.png)
and with SUMO 1.9.2:
![most_with_sumo1 9 2_2](https://user-images.githubusercontent.com/4274367/123811098-7a3da180-d8e2-11eb-8029-0733b75d7b5e.png)

The output of SUMO 1.9.2 says:
```
Eclipse SUMO sumo Version 1.9.2
 Build features: Linux-5.12.9-arch1-1 x86_64 GNU 11.1.0 Release Proj GUI
SWIG GDAL FFmpeg OSG
 Copyright (C) 2001-2021 German Aerospace Center (DLR) and others;
https://sumo.dlr.de
....
Simulation ended at time: 50400.00
Reason: The final simulation step has been reached.
Performance:
 Duration: 3203.15s
 Real time factor: 11.2389
 UPS: 374543.147099
 UPS-Persons: 51272.532918
Vehicles:
 Inserted: 46842
 Running: 32
 Waiting: 0
Teleports: 52 (Jam: 15, Yield: 32, Wrong Lane: 5)
Emergency Stops: 2
Persons:
 Inserted: 45000
 Running: 26
 Jammed: 2560
Statistics (avg):
 RouteLength: 6839.22
 Speed: 6.92
 Duration: 6406.78
 WaitingTime: 35.84
 TimeLoss: 121.52
 DepartDelay: 0.45
Pedestrian Statistics (avg of 31421 walks):
 RouteLength: 450.72
 Duration: 385.63
 TimeLoss: 57.15
Ride Statistics (avg of 45216 rides):
 WaitingTime: 38.11
 RouteLength: 6073.44
 Duration: 589.52
 Bus: 5967
 Bike: 3455
```

Currently, we are unsure why this might happen and which of the behavior shown above is actually the desired one. 
Do you have an idea what might be the cause of this behavior?
Also, is 1.3.1 the most recent version of SUMO capable to run this scenario?

Thank you and kind regards
Alexander

Edit: This was tested with the current master (7cee150a6631663e173df463180ec26ec1ef9549)
